# Opérations avec Python - Prise en main


--- 

Ce notebook sert d'initiation sur Python et les différentes librairies utiles pour le traitement d'images.
Dans le cadre des travaux pratiques de ce cours, nous allons principalement utiliser 3 librairies Python : 
- NumPy, pour le calcul mathématique et la manipulation de matrices ;
- Matplotlib pour la visualisation graphique des données ;
- OpenCV (cv2) pour la manipulation et le traitement d'images.

Pour plus de détails sur Python, NumPy, Matplotlib et OpenCV, un grand nombre de ressources sont disponibles sur https://pythonprogramming.net/, y compris plusieurs séries de vidéos YouTube.

La documentation complète de Python 3 et des librairies qui seront utilisées sont disponibles ici :
- Python 3 : https://docs.python.org/fr/3/
- NumPy : https://docs.scipy.org/doc/numpy-1.15.0/reference/index.html
- Matplotlib : https://matplotlib.org/3.1.1/index.html
- OpenCV : https://docs.opencv.org/4.1.1/index.html (bon courage !)

## Ex. 0 : Démarrage

Python est un langage très complet et utilisé dans de nombreux domaines, du développement Web à la robotique.

Dans cette série de TP, nous l'utiliserons pour la vision informatique, le calcul mathématique et la science des données.

Commencez par importer les librairies nécessaires.

In [2]:
# Affichage avec la bibliothèque graphique intégrée à Notebook
%matplotlib inline

# Librairies Matplotlib, NumPy et OpenCV
import matplotlib.pyplot as plt
import numpy as np
import cv2 #OpenCV

# Librairies supplémentaires pour certaines parties du TP
from sklearn.cluster import MiniBatchKMeans

Et définissez le chemin d'accès à la base d'images (utilisée ultérieurement)

In [3]:
# A changer si le dossier ne se situe pas à cet endroit
path_base = 'images_initiation/'

## Ex. 1 : Python et NumPy en quelques lignes

**1.**

Calculez $\log(\cos(1-(1+1)/2))$ et $\sqrt{-1}$ avec NumPy

In [86]:
np.log(np.cos(1 - (1 + 1)/2 ))

In [87]:
x = complex(-1,0)  # On crée le complexe -1 + 0j
np.sqrt(x)

---
**2.**

Utilisez sur 2 cellules différentes les fonctions print et whos.

In [88]:
help(print)

In [89]:
whos

Que font les instructions Python help et %whos ?

**_REPONSE :_**

---
**3.**

Créez une variable a à laquelle vous affecterez le résultat du calcul $2(3+ 2)$. Puis enlevez un à la valeur de la variable a.

In [90]:
a = 2*(3+2)
a = a-1
a

Vérifiez quelles sont les variables connues du notebook (et que a est bien connue et quelle a le type attendu)

In [91]:
#whos

--- 
**4.**

Pour créer une boucle déterministe, utilisez la fonction range pour faire varier un entier.

In [93]:
N = 5
for i in range(N):
    print(i)

La foncion *range* avec le paramètre *_N_* fait varier un nombre *_i_* entre 0 et *_N-1_* (contrairement à Matlab, ou en Pascal, où on fait varier *_i_* entre 1 et *_N_*).

De la même manière que précédemment, faites varier le nombre *i* entre 10 et 1 en sens decroissant avec un pas de 2.

In [11]:
#A compléter
...

---
**5.**

D'un point de vue numérique, une image est tout simplement une matrice. Le traitement d'image s'apparente donc à l'application d'algorithmes sur des matrices. 

Créez la matrice
$A = \left[\begin{array}{lll}
1 & 2 & 3\\
4 & 5 & 6\\
−1 & 0 & 1\\
1 & 1 & 2
\end{array}\right]$

In [94]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [-1, 0, 1],
    [1, 1, 2]
])
A

Affichez la taille et les dimensions de la matrice A créée.

In [95]:
A.size

In [14]:
A.shape

(4, 3)

Affichez le nombre de dimensions de A.

In [16]:
A.ndim

2

Affichez la deuxième colonne de A.

In [17]:
A[:,1]

array([2, 5, 0, 1])

Créez un sous-tableau s composé des 2ème et 3ème lignes
de A.

In [18]:
s = A[1:3, :]
s

array([[ 4,  5,  6],
       [-1,  0,  1]])

---
**6.**


Ce petit exercice n°6 ne vous paraîtra pas être grand chose, mais croyez-moi, c'est un point méga important. Cela peut-être cause de nombreux bugs en traitement d'images, lorsqu'on applique des algorithmes. Donc, prenez des notes sur ce point-là, c'est mon petit conseil 

Affichez le type des élements de la matrice A.

In [19]:
A.dtype

dtype('int64')

Il est important dans le cadre de la manipulation de matrices de bien connaître le type des éléments que nous manipulons :
- Est-ce un naturel (uint), un entier (int), un réel (float), un booléen (bool), un complexe (complex) ?
- En combien de bits l'élement est codé ? (8, 16, 32, 64)

Vous trouverez ci-dessous les types de données disponibles sous NumPy.

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

Un exemple concret de mauvaise manipulation de matrice :

In [31]:
B = np.full((2,2), 255, dtype = np.uint16)
C = np.full((2,2), 255, dtype = np.uint8)
print("B :\n{}\n".format(B))
print("C :\n{}\n".format(C))

B :
[[255 255]
 [255 255]]

C :
[[255 255]
 [255 255]]



In [40]:
print("B+1 :\n{}\n".format(B+1))

B+1 :
[[256 256]
 [256 256]]



In [41]:
print('B+1 :\n{} '.format(B+1))

B+1 :
[[256 256]
 [256 256]] 


In [42]:
print("C+1 :\n{}\n ".format(C+1))

C+1 :
[[0 0]
 [0 0]]
 


Pour quelle(s) raison(s) avons-nous obtenu ces résultats précédents ?

**_REPONSE :_**

---
**7.**

La multiplication de matrices sur Python peut se faire avec NumPy. Tout d'abord, créez 2 matrices A et B, de taille NxN.

In [24]:
N = 2
A = np.random.randint(0,10,(N,N))
B = np.random.randint(0,10,(N,N))
print('A : \n{}'.format(A))
print('B : \n{}'.format(B))

A : 
[[9 6]
 [5 3]]
B : 
[[6 0]
 [4 2]]


Que fait la fonction *multiply* de NumPy (équivalent à *A*B*) ?

In [25]:
np.multiply(A,B)

array([[54,  0],
       [20,  6]])

Que fait la fonction *dot* de NumPy (équivalent à A@B) ?

In [26]:
np.dot(A,B)

array([[78, 12],
       [42,  6]])

**_REPONSE :_**

Calculez la transposée de A multipliée par B (avec numpy.dot)

In [27]:
np.dot(A.T,B)

array([[74, 10],
       [48,  6]])

---
**8.**


Ce petit exercice est également important car on va énormément utiliser les masques dans cette matière. Cela va être difficle au début de les maîtriser parfaitement, mais si vous y arrivez, vous allez gagner beaucoup de temps (que ce soit dans l'écriture des codes comme dans les temps d'exécution). Cela permet d'éviter de faire des boucles, et des boucles de boucles, voire également des boucles de boucles de boucles de boucles (déjà fait, pas terrible).


Créez une matrice A de taille 5X5 comprenant des valeurs aléatoires entières entre 0 et 9.

In [79]:
A = np.random.randint(0,10,(5,5))
print('A : \n{}'.format(A))

A : 
[[6 0 9 5 8]
 [8 8 0 8 6]
 [9 8 1 1 4]
 [4 1 2 3 6]
 [3 5 3 7 5]]


Nous allons maintenant créer un masque. Avant que vous me posiez la question, un masque est une matrice de booléen (0 ou 1), tout simplement. Créez un masque M de la même taille que A.

In [85]:
M = np.random.randint(0,2,(5,5))
print('M : \n{}'.format(M))


M : 
[[0 0 0 1 1]
 [0 0 0 1 0]
 [1 1 1 0 1]
 [1 0 1 1 0]
 [1 1 1 0 1]]


Comme précisé précédemment, nous voulons un tableau de booléen. En rappel à l'exercice 6, vérifiez que le type de la matrice est adéquat. Si ce n'est pas le cas, utilisez la fonction astype pour avoir une matrice de booléen. Pour être sur que votre matrice est du bon type, vous devriez voir en l'affichant, non pas des 0 et 1, mais des False et True.

In [81]:
# A compléter
# Vérification du type de données de la matrice
...
# Changement du type de données et affichage de la matrice (si nécessaire)
...

Ellipsis

Appliquez maintenant le masque sur la matrice via la commande suivante :

In [82]:
B = A[M]
print('A : \n{}'.format(A))
print('M : \n{}'.format(M))
print('B : \n{}'.format(B))

A : 
[[6 0 9 5 8]
 [8 8 0 8 6]
 [9 8 1 1 4]
 [4 1 2 3 6]
 [3 5 3 7 5]]
M : 
[[False  True False  True  True]
 [False  True False False False]
 [False False False False False]
 [ True  True  True False False]
 [False False False  True False]]
B : 
[0 5 8 8 4 1 2 7]


Que renvoit B (l'application du masque M sur la matrice A) ?

**_REPONSE :_** 

Maintenant, nous allons voir plusieurs applications vachement utiles des masques. Tout d'abord, on va en créer de différentes manières.

Que renvoient les commandes suivantes ?

In [ ]:
# Commande 1
A<5

In [ ]:
# Commande 2
A == 2

In [ ]:
# Commande 3
np.logical_and(A>4,A<7)

In [ ]:
# Commande 4
np.logical_xor(A>4,A<6)

**_REPONSE :_**

Pour finir avec cet exercice, nous allons voir plusieurs applications possibles des masques.

Que renvoient les commandes suivantes ?

In [ ]:
# Commande 1
B = A.copy()
B[A<5] = 0
print('B :\n{}'.format(B))

In [ ]:
#Commande 2
C = A.copy()
C[A>7]*=2
print('C :\n{}'.format(C))

In [ ]:
#Commande 3 
D = A.copy()
D[(A%2).astype(bool)]-=1
print('D :\n{}'.format(D))

**_REPONSE :_** 

---
**9.**

Pour gérer des fichiers, on utilisera la bibliothèque os:

In [ ]:
import os
os.path.abspath(os.curdir)

In [ ]:
os.listdir()